version: "2"
services:
  redis:
    image: redis:alpine
    container_name: "Redis_Container"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    ports:
      - "6379:6379"

    environment:
      - REDIS_REPLICATION_MODE=master

  app:
    build: ./app
    container_name: "FlaskApp"
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:5.7
    container_name: "FlaskApp_DB"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro